# MBG1032 Biyoistatistik Ders Notları

## Kaynaklar

* Kitap1: [Principles of Biostatistics](https://www.taylorfrancis.com/books/mono/10.1201/9780429489624/principles-biostatistics-marcello-pagano-kimberlee-gauvreau) (*Marcello Pagano, Kimberlee Gauvreau*)
* Kitap2: [Biostatistics for the Biological and Health Sciences](https://www.pearson.com/en-us/subject-catalog/p/biostatistics-for-the-biological-and-health-sciences/P200000007576/9780137863792) (*Mario F. Triola, Marc M. Triola,Jason Roy*)
* Kitap3: [Introduction to Biostatistics Using R](https://books.google.com.tr/books/about/Introduction_to_Biostatistics_Using_R.html?id=MLO0zgEACAAJ&redir_esc=y) (*Mohsen Nady*)
* Kitap4: [R Programı İle Temel İstatistiksel Yöntemler Uygulamalı İstatistik](https://www.turcademy.com/tr/kitap/r-programi-ile-temel-istatistiksel-yontemler-uygulamali-istatistik-istatistik-yontemler-9789750263682) *Turcademy* üzerinden ücretsiz olarak erişilebilir.

## Ders1

**Teorik** (*21 Şubat 2024*): İlk derste, R programı çalıştırılabilecek ortamlar tanıtıldı. Ayrıca "[Is Most Published Research Wrong?](https://www.youtube.com/watch?v=42QuXLucH3Q)" başlıklı videodan bahsedildi. Söz konusu videoda *p-value* değerlerinin istatistik gücü oldukça zayıf şekilde bilimsel makalelerde kullanıldığı ve bu yüzden makalelerin tekrarlanabilirliğinin (*reproducability*) düşük olduğundan bahsedildi.

**Uygulama** (*26 Şubat 2024*): R Temelleri [Sunum](uygulama01.qmd). Bu içerik için kullanılan ek kaynak, "[An Introduction to R](https://intro2r.com/getting-started.html)" adlı online kitap.

<!--  Uygulamada kullanılacak dosyalar: [mtcars (Excel)](files/mtcars.xlsx) -->

## Ders2

**Teorik** (*28 Şubat 2024*): Veri setinin merkezini belirleyen ortalama ve mediandan bahsedildi. Veri setinin dağınıklığını özetleyen sayısal yöntemler (varyans, standart sapma) ve görsel yöntemler (histogram, boxplot) tanıtıldı. [Sunum linki](ders02.qmd)

**Uygulama** (*4 Mart 2024*): [iris.xlsx](files/iris.xlsx) dosyasını kullanarak, Excel'de hücre aralıklarını seçme, <kbd>Ctrl</kbd> ve <kbd>Shift</kbd> tuşları ile hızlı seçim ve gezinme gösterildi. Tek bir sütün için ortalama, medyan, 1. ve 3. çeyrek dilim hesaplama ve standard sapma hesabı yapıldı. Excel'de formüllerin başka hücrelere uygulanması gösterildi. Excel'in yeni versiyonunda Boxplot ve Histogram grafikleri çizilebileceği tartışıldı.

## Ders03

**Teorik** (*6 Mart 2024*): Olaslık hesabına dair özellikler, küme prensibi üzerinden anlatıldı. Normal dağılımın özellikleri tanıtıldı.

**Uygulama** (*11 Mart 2024*):